title: Andross
description: There is no such thing as a sad unicorn.

#for the navbar links.
custom_links:
  - title: Luxury Properties
    url: http://www.sflivingspace.com/luxury-properties/

client:
  market:
  name: andross
  brand: 'nintendo'
  brokerage: '#'
  address: 123 fake st.
  phone: 402-402-4002
  email: sample@email.com
  #Dont Include http://
  url: getvyral.com
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: '/homevalue/'
  homeeval_txt: Home Evaluation
  homesearch: /homesearch/
  homesearch_txt: Home Search
  VR_form:

# social links
socials:
  facebook: 'http://facebook.com'
  linkedin: 'http://linked.com'
  gplus: 'http://plus.google.com'
  youtube: 'http://youtube.com'
  twitter: 'http://twitter.com'
  instagram: '#'
  pinterest: '#'
  zillow: 'http://zillow.com'
  trulia: 'http://trulia.com'
  yelp: 'http://yelp.com'
  podcast: 'http://#.com'

#podcast settings
podcast:
  # Something Real Estate Podcast
  title:
  categories:
    - category: 'News &amp; Politics'
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- market -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --client brand-- - your professional --market-- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:

#layout options
# if we want review buttons --
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: http://0.design-milk.com/images/2015/12/iso_rynth03-pattern.jpg
  hero_logo_path: http://design.ubuntu.com/wp-content/uploads/logo-ubuntu_st_no%C2%AE-white-hex.png
  hero_background_hex: "#123456"
  client_headshot_path: http://i.imgur.com/RQeCxbx.png

#colors
brand_hex: '#123456'
theme_text: '#353535'
theme-color: '#ffffff'
fontcolor_hex: "#353535"
testimonial_fontcolor: '#fff'

#make testimonial container match brand color
testimonial-container-brand_color: true

#experimental, don't use yet
theme_color: "#fff"
