title: Dean Aguilar Group Real Estate Video Blog
description: There is no such thing as a sad unicorn.

about_markdown: hello
#for the navbar links.
custom_links:
  # - title: Luxury Properties
  #   url: http://www.sflivingspace.com/luxury-properties/

client:
  market: San Diego County
  name: Dean Aguilar
  brand: Dean Aguilar Group
  brokerage: '#'
  address: 6436 Mt Acre way<br>San Diego, 92111
  phone: (619) 550-7892
  email: dean@deanaguilargroup.com
  #Dont Include http://
  url: www.deanaguilargroup.com
  # if forms put '/homevalue/' or '/homesearch/'
  homeeval: 'http://www.chulahomevalue.com/'
  homeeval_txt: Home Evaluation
  homesearch: 'http://www.viewsandiegoareahomes.com'
  homesearch_txt: Home Search
  VR_form:

# social links
socials:
  facebook: 'http://facebook.com'
  linkedin: 'http://linked.com'
  gplus: 'http://plus.google.com'
  youtube: 'http://youtube.com'
  twitter: 'http://twitter.com'
  instagram: '#'
  pinterest: '#'
  zillow: 'http://zillow.com'
  trulia: 'http://trulia.com'
  yelp: 'http://yelp.com'
  podcast: 'http://#.com'

#podcast settings
podcast:
  # Something Real Estate Podcast
  title: Dean Aguilar Group Real Estate Podcast
  categories:
    - category: 'News &amp; Politics'
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Diego Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Dean Aguilar Group - your professional San Diego Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Dean Aguilar

#layout options
# if we want review buttons --
review_sm_icons: false
audit_header: false

#image settings
images:
  hero_image_path: /img/blog_background.jpg
  hero_logo_path: /img/Dean-logo.png
  hero_text: Real Estate Video Blog
  hero_background_hex: "#4F7588"
  client_headshot_path: /img/dean-square.png

#colors
brand_hex: '#4F7588'
theme_text: '#353535'
theme_color: '#ffffff'
fontcolor_hex: "#353535"
testimonial_fontcolor: '#fff'

#make testimonial container match brand color
testimonial-container-brand_color: true
